Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -21,20 +21,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.23.2
-
-      - name: Generate go.sum
+      - name: Install dependencies
         run: |
-          cd go-test
-          go mod tidy
+          go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
+          go get -v ./...
+      - name: Install the application
+        run: go install ./...
 
       - name: Run tests
-        run: |
-          cd go-test
-          go test -v ./...
+        run: go test -v ./... || exit 1  # Fail the job if tests fail
 
   build:
     runs-on: ubuntu-latest
