Update node.yml

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -68,68 +68,16 @@ jobs:
       - name: Read version from VERSION file
         id: read_version
         run: |
-          # Read the entire content of the VERSION file and trim any surrounding whitespace
-          VERSION=$(cat VERSION)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "Version extracted: $VERSION"
-
-      - name: Build Docker image with extracted version
-        run: |
-          docker build -t soubarniya/mynode:${{ env.VERSION }} .
-          docker images
-
-      - name: Push Docker image with extracted version
-        if: github.ref == 'refs/heads/main'
-        run: |
-
-          docker push soubarniya/mynode:${{ env.VERSION }}
-
-  K8s-Manifest-Update:
-    runs-on: ubuntu-latest
-    needs: Docker-Build-Push
-    if: github.ref == 'refs/heads/main' # Only run this job if the branch is main
-
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4
-      - name: Read version from VERSION file
-        id: read_version
-        run: |
-          # Read the entire content of the VERSION file and trim any surrounding whitespace
-          VERSION=$(cat VERSION)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "Version extracted: $VERSION"
-      - name: Check for docker image
-        run: |
-          docker pull soubarniya/mynode:${{ env.VERSION }}
-          docker images
-      - name: Update Kubernetes manifest
-        run: |
-          pwd
-          ls -la
-          git clone https://github.com/Soubarniya/argocd.git
-          ls -la
-          cd argocd
-          ls -la
-          # Create a new branch with a unique name (e.g., "update-node-version-${{ env.VERSION }}")
-          git checkout -b node-version-${{ env.VERSION }}
-          sed -i "s|image: soubarniya/mynode:.*|image: soubarniya/mynode:${{ env.VERSION }}|" node.yaml
-          git status
-          git diff
-          cat node.yaml
-          # Configure Git
-          # git init .
-          git config --global user.email "leosphere2001@gmail.com"
-          git config --global user.name "Soubarniya"
-
-          # Commit and push changes if there’s an update
-          if git diff --exit-code --quiet; then
-            echo "No changes to commit."
+          if [ -f go-test/VERSION ]; then
+            VERSION=$(cat go-test/VERSION | xargs)
+            echo "VERSION=$VERSION" >> $GITHUB_ENV
           else
-            git add node.yaml
-            git commit -m "Updated node.yaml with version ${{ env.VERSION }} | GitHub Actions Pipeline"
-            git pull --rebase origin node-version-${{ env.VERSION }} || echo "Branch doesn't exist remotely, continuing."
-
-            # git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN}}@github.com/Soubarniya/argocd.git
-            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN}}@github.com/Soubarniya/argocd.git node-version-${{ env.VERSION }}
+            echo "VERSION file not found!"
+            exit 1
           fi
+      - name: Build and push Docker image
+        run: |
+          cd go-test
+          docker build -t manisankardivi/node:${{ env.VERSION }} .
+          docker push manisankardivi/node:${{ env.VERSION }}
+
